// GENERATED by ontology/codegen.ts from metrics.yaml. Do not edit.
// Run `pnpm codegen`.

export const TRANSFORMS = ["none","share_of_total","rank","bucket","rate","time_series"] as const;
export type Transform = (typeof TRANSFORMS)[number];

export interface MetricDef {
  label: string;
  description: string;
  source: string;
  measure: string;
  transform: Transform;
  viz: string;
  phase: number;
  /** What one row IS. [account_id] alone means a single scalar. */
  grain: string[];
  filter?: string;
  dimension?: string;
  secondaryMeasure?: string;
  limit?: number;
  ascending?: boolean;
  compareTo?: string;
}

export const METRICS: Record<string, MetricDef> = {
  "completion_rate": { label: "Show completion rate", description: "Share of started shows that were finished rather than abandoned.", source: "sem.user_title", measure: "count(*) FILTER (WHERE status = 'watched')::float / nullif(count(*),0)", transform: "none", viz: "stat", phase: 2, grain: ["account_id"], filter: "kind = 'show' AND status IN ('watched','abandoned')" },
  "franchise_coverage": { label: "Franchise coverage", description: "How much of each franchise the user has seen.", source: "sem.user_franchise_coverage", measure: "watched_count", transform: "rate", viz: "progress_list", phase: 2, grain: ["account_id","collection_id"], secondaryMeasure: "total_count" },
  "genre_distribution": { label: "Genre distribution", description: "Share of watched titles by genre.", source: "sem.user_taste_affinity", measure: "n_titles", transform: "share_of_total", viz: "donut", phase: 1, grain: ["account_id","concept_id"], filter: "node_type = 'concept' AND scheme = 'genre'" },
  "rating_distribution": { label: "Rating distribution", description: "How the user's own ratings are spread across the half-star scale.", source: "sem.user_title", measure: "count_distinct(title_id)", transform: "none", viz: "histogram", phase: 1, grain: ["account_id","rating"], filter: "status = 'watched' AND rating IS NOT NULL", dimension: "rating" },
  "theme_distribution": { label: "Theme distribution", description: "Share of watched titles by curated theme. The interesting one — this is our vocabulary, not a provider's.", source: "sem.user_taste_affinity", measure: "n_titles", transform: "share_of_total", viz: "donut", phase: 2, grain: ["account_id","concept_id"], filter: "node_type = 'concept' AND scheme = 'theme'" },
  "top_directors": { label: "Most-watched directors", description: "Directors ranked by count of watched titles, with the user's mean rating.", source: "sem.user_taste_affinity", measure: "n_titles", transform: "rank", viz: "ranked_list", phase: 1, grain: ["account_id","person_id"], filter: "node_type = 'person' AND predicate = 'directed_by'", secondaryMeasure: "avg_rating", limit: 10 },
  "under_watched_genres": { label: "Under-watched genres", description: "The user's genre distribution compared against the corpus distribution. The first genuinely analytical metric rather than a descriptive one.", source: "sem.user_taste_affinity", measure: "share_delta", transform: "rank", viz: "ranked_list", phase: 2, grain: ["account_id","concept_id"], limit: 5, ascending: true, compareTo: "sem.corpus_genre_distribution" },
  "viewing_over_time": { label: "Viewing over time", description: "Titles finished per month.", source: "sem.user_viewing", measure: "count(*)", transform: "time_series", viz: "sparkline", phase: 1, grain: ["account_id","month"], filter: "date_precision <> 'unknown'", dimension: "date_trunc('month', watched_on)" },
  "watchlist_aging": { label: "Watchlist aging", description: "How long things have been sitting unwatched.", source: "sem.user_title", measure: "count_distinct(title_id)", transform: "bucket", viz: "bar", phase: 1, grain: ["account_id","bucket"], filter: "status = 'watchlist'", dimension: "width_bucket(days_on_watchlist, ARRAY[30,90,180,365])" },
};

export type MetricName = keyof typeof METRICS;
