/**
 * Compiles ontology/ontology.yaml into the artifacts the rest of the system uses.
 *
 *   src/lib/ontology/generated.ts   TS types, domain/range maps, path weights, narration
 *   drizzle/generated/ontology.sql  CHECK constraints + core.assert_edge_valid() trigger
 *   docs/ontology-reference.md      human-readable predicate table
 *
 * Output MUST be deterministic — CI runs `pnpm codegen && git diff --exit-code`,
 * so any nondeterminism (map ordering, timestamps) breaks the build. Never write
 * a generated-at timestamp into these files.
 *
 * Run: pnpm codegen
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { parse } from 'yaml';

type Attribute = {
  type: string;
  values?: string[];
  nullable?: boolean;
  min?: number;
  max?: number;
};
type Predicate = {
  label: string;
  inverse: string;
  domain: string[];
  range: string[];
  storage: string;
  provenance: string[];
  path_weight?: number;
  path_weight_expr?: string;
  symmetric?: boolean;
  structural?: boolean;
  sparse?: boolean;
  excluded_from_path_intermediates?: boolean;
  attributes?: Record<string, Attribute>;
  narration: string;
  narration_inverse?: string;
  narration_with_attributes?: string;
};
type EntityType = {
  table: string;
  label_field: string;
  image_field?: string;
  graph_node?: boolean;
  public_page?: boolean;
  part_of?: string;
  subtypes?: { discriminator: string; values: string[] };
};
type Ontology = {
  version: number;
  entity_types: Record<string, EntityType>;
  concept_schemes: Record<string, { curated: boolean; source: string; hierarchical: boolean }>;
  predicates: Record<string, Predicate>;
  path_ranking: Record<string, number>;
};

const BANNER = '// GENERATED BY `pnpm codegen` FROM ontology/ontology.yaml — DO NOT EDIT.';
const SQL_BANNER = '-- GENERATED BY `pnpm codegen` FROM ontology/ontology.yaml -- DO NOT EDIT.';

const onto = parse(readFileSync('ontology/ontology.yaml', 'utf8')) as Ontology;
const predicateNames = Object.keys(onto.predicates).sort();
const entityNames = Object.keys(onto.entity_types).sort();

/** `concept:theme` -> `concept`. Subtype constraints are checked separately. */
const baseType = (t: string): string => t.split(':')[0]!;
const subType = (t: string): string | null => t.split(':')[1] ?? null;

function validate(): void {
  const errors: string[] = [];
  for (const [name, p] of Object.entries(onto.predicates)) {
    for (const t of [...p.domain, ...p.range]) {
      if (!onto.entity_types[baseType(t)]) errors.push(`${name}: unknown type "${t}"`);
      const st = subType(t);
      if (st) {
        const decl = onto.entity_types[baseType(t)]?.subtypes;
        if (!decl) errors.push(`${name}: "${baseType(t)}" declares no subtypes but "${t}" used`);
        else if (!decl.values.includes(st))
          errors.push(`${name}: "${st}" not a valid ${baseType(t)} subtype`);
      }
    }
    if (!p.inverse) errors.push(`${name}: missing inverse`);
    if (!p.narration) errors.push(`${name}: missing narration template`);
    if (!p.structural && p.path_weight === undefined)
      errors.push(`${name}: non-structural predicate needs path_weight`);
  }
  if (errors.length) {
    console.error('ontology validation FAILED:\n' + errors.map((e) => `  - ${e}`).join('\n'));
    process.exit(1);
  }
}

function write(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content.endsWith('\n') ? content : content + '\n');
  console.log(`  wrote ${path}`);
}

const q = (s: string): string => `'${s.replace(/'/g, "\\'")}'`;

// ---------------------------------------------------------------- TypeScript
function emitTypes(): string {
  const L: string[] = [BANNER, ''];
  L.push(`export const ONTOLOGY_VERSION = ${onto.version};`, '');
  L.push(`export const ENTITY_TYPES = [${entityNames.map(q).join(', ')}] as const;`);
  L.push('export type EntityType = (typeof ENTITY_TYPES)[number];', '');
  L.push(`export const PREDICATES = [${predicateNames.map(q).join(', ')}] as const;`);
  L.push('export type Predicate = (typeof PREDICATES)[number];', '');

  const graphNodes = entityNames.filter((n) => onto.entity_types[n]!.graph_node);
  L.push(`export const GRAPH_NODE_TYPES = [${graphNodes.map(q).join(', ')}] as const;`);
  L.push('export type GraphNodeType = (typeof GRAPH_NODE_TYPES)[number];', '');

  L.push('export interface PredicateSpec {');
  L.push('  readonly label: string;');
  L.push('  readonly inverse: string;');
  L.push('  readonly domain: readonly string[];');
  L.push('  readonly range: readonly string[];');
  L.push('  readonly storage: string;');
  L.push('  readonly provenance: readonly string[];');
  L.push('  readonly pathWeight: number | null;');
  L.push('  readonly symmetric: boolean;');
  L.push('  readonly structural: boolean;');
  L.push('  readonly sparse: boolean;');
  L.push('  readonly excludedFromPathIntermediates: boolean;');
  L.push('  readonly narration: string;');
  L.push('  readonly narrationInverse: string | null;');
  L.push('  readonly narrationWithAttributes: string | null;');
  L.push('}', '');

  L.push('export const PREDICATE_SPECS: Readonly<Record<Predicate, PredicateSpec>> = {');
  for (const name of predicateNames) {
    const p = onto.predicates[name]!;
    L.push(`  ${name}: {`);
    L.push(`    label: ${q(p.label)},`);
    L.push(`    inverse: ${q(p.inverse)},`);
    L.push(`    domain: [${p.domain.map(q).join(', ')}],`);
    L.push(`    range: [${p.range.map(q).join(', ')}],`);
    L.push(`    storage: ${q(p.storage)},`);
    L.push(`    provenance: [${p.provenance.map(q).join(', ')}],`);
    L.push(`    pathWeight: ${p.path_weight ?? 'null'},`);
    L.push(`    symmetric: ${Boolean(p.symmetric)},`);
    L.push(`    structural: ${Boolean(p.structural)},`);
    L.push(`    sparse: ${Boolean(p.sparse)},`);
    L.push(`    excludedFromPathIntermediates: ${Boolean(p.excluded_from_path_intermediates)},`);
    L.push(`    narration: ${q(p.narration)},`);
    L.push(`    narrationInverse: ${p.narration_inverse ? q(p.narration_inverse) : 'null'},`);
    L.push(
      `    narrationWithAttributes: ${p.narration_with_attributes ? q(p.narration_with_attributes) : 'null'},`,
    );
    L.push('  },');
  }
  L.push('};', '');

  const traversable = predicateNames.filter((n) => !onto.predicates[n]!.structural);
  L.push('/** Structural predicates are excluded: composition is not a connection. */');
  L.push(`export const TRAVERSABLE_PREDICATES = [${traversable.map(q).join(', ')}] as const;`, '');

  L.push('/** Lower cost = more meaningful in an explanation path. See docs/graph.md. */');
  L.push('export const PATH_WEIGHTS: Readonly<Record<string, number>> = {');
  for (const n of traversable) L.push(`  ${n}: ${onto.predicates[n]!.path_weight},`);
  L.push('};', '');

  L.push('export const PATH_RANKING = {');
  for (const [k, v] of Object.entries(onto.path_ranking)) {
    L.push(`  ${k.replace(/_(.)/g, (_, c: string) => c.toUpperCase())}: ${v},`);
  }
  L.push('} as const;', '');

  L.push('export const ENTITY_TABLES: Readonly<Record<EntityType, string>> = {');
  for (const n of entityNames) L.push(`  ${n}: ${q(onto.entity_types[n]!.table)},`);
  L.push('};', '');
  return L.join('\n');
}

// ----------------------------------------------------------------------- SQL
function emitSql(): string {
  const L: string[] = [SQL_BANNER, ''];
  L.push('-- The ontology is enforced by the database, not by application convention.');
  L.push('-- An edge with an invalid predicate or a domain/range violation is rejected');
  L.push('-- at write time, in every code path, including ad hoc psql.', '');

  L.push('ALTER TABLE core.edge DROP CONSTRAINT IF EXISTS edge_predicate_declared;');
  L.push('ALTER TABLE core.edge ADD CONSTRAINT edge_predicate_declared');
  const storedInEdge = predicateNames.filter((n) => onto.predicates[n]!.storage === 'core.edge');
  L.push(`  CHECK (predicate IN (${storedInEdge.map((p) => `'${p}'`).join(', ')}));`, '');

  L.push(
    'ALTER TABLE core.edge_derived DROP CONSTRAINT IF EXISTS edge_derived_predicate_declared;',
  );
  L.push('ALTER TABLE core.edge_derived ADD CONSTRAINT edge_derived_predicate_declared');
  const derived = predicateNames.filter((n) => onto.predicates[n]!.storage === 'core.edge_derived');
  L.push(`  CHECK (predicate IN (${derived.map((p) => `'${p}'`).join(', ')}));`, '');

  L.push('ALTER TABLE core.credit DROP CONSTRAINT IF EXISTS credit_predicate_declared;');
  L.push('ALTER TABLE core.credit ADD CONSTRAINT credit_predicate_declared');
  const credit = predicateNames.filter((n) => onto.predicates[n]!.storage === 'core.credit');
  L.push(`  CHECK (predicate IN (${credit.map((p) => `'${p}'`).join(', ')}));`, '');

  L.push('-- Domain/range enforcement, including concept-scheme and organization-kind subtypes.');
  L.push('CREATE OR REPLACE FUNCTION core.assert_edge_valid() RETURNS trigger AS $$');
  L.push('DECLARE ok boolean := false; subtype_ok boolean := true;');
  L.push('BEGIN');
  L.push('  CASE NEW.predicate');
  for (const name of [...storedInEdge, ...derived].sort()) {
    const p = onto.predicates[name]!;
    L.push(`    WHEN '${name}' THEN`);
    L.push(
      `      ok := NEW.subject_type IN (${[...new Set(p.domain.map(baseType))].map((t) => `'${t}'`).join(', ')})`,
    );
    L.push(
      `        AND NEW.object_type IN (${[...new Set(p.range.map(baseType))].map((t) => `'${t}'`).join(', ')});`,
    );
    const conceptSub = p.range
      .filter((r) => baseType(r) === 'concept')
      .map(subType)
      .filter(Boolean);
    if (conceptSub.length) {
      L.push(`      IF ok AND NEW.object_type = 'concept' THEN`);
      L.push(
        `        SELECT scheme IN (${conceptSub.map((s) => `'${s}'`).join(', ')}) INTO subtype_ok`,
      );
      L.push('          FROM core.concept WHERE id = NEW.object_id;');
      L.push('      END IF;');
    }
    const orgSub = p.range
      .filter((r) => baseType(r) === 'organization')
      .map(subType)
      .filter(Boolean);
    if (orgSub.length) {
      L.push(`      IF ok AND NEW.object_type = 'organization' THEN`);
      L.push(`        SELECT kind IN (${orgSub.map((s) => `'${s}'`).join(', ')}) INTO subtype_ok`);
      L.push('          FROM core.organization WHERE id = NEW.object_id;');
      L.push('      END IF;');
    }
  }
  L.push('    ELSE');
  L.push(`      RAISE EXCEPTION 'predicate % is not declared in ontology.yaml', NEW.predicate;`);
  L.push('  END CASE;');
  L.push('  IF NOT ok THEN');
  L.push(`    RAISE EXCEPTION 'ontology violation: % (% -> %) breaks the declared domain/range',`);
  L.push('      NEW.predicate, NEW.subject_type, NEW.object_type;');
  L.push('  END IF;');
  L.push('  IF NOT coalesce(subtype_ok, false) THEN');
  L.push(
    `    RAISE EXCEPTION 'ontology violation: % object fails its declared subtype constraint', NEW.predicate;`,
  );
  L.push('  END IF;');
  L.push('  RETURN NEW;');
  L.push('END;');
  L.push('$$ LANGUAGE plpgsql;', '');
  L.push('-- Predicate metadata IN the database: domain, range, subtype constraints,');
  L.push('-- inverses and path weights. The validation trigger below is generic logic');
  L.push('-- over this table, NOT generated branches — so adding a predicate changes');
  L.push('-- data, never code.');
  L.push('CREATE TABLE IF NOT EXISTS core.predicate_meta (');
  L.push('  predicate text PRIMARY KEY,');
  L.push('  label text NOT NULL,');
  L.push('  inverse text NOT NULL,');
  L.push('  inverse_label text NOT NULL,');
  L.push('  storage text NOT NULL,');
  L.push('  domain_types text[] NOT NULL,');
  L.push('  range_types text[] NOT NULL,');
  L.push('  range_concept_schemes text[],');
  L.push('  range_org_kinds text[],');
  L.push('  path_weight numeric,');
  L.push('  is_symmetric boolean NOT NULL DEFAULT false,');
  L.push('  is_structural boolean NOT NULL DEFAULT false,');
  L.push('  excluded_from_path_intermediates boolean NOT NULL DEFAULT false');
  L.push(');');
  L.push('TRUNCATE core.predicate_meta;');
  L.push('INSERT INTO core.predicate_meta (predicate, label, inverse, inverse_label, storage,');
  L.push('  domain_types, range_types, range_concept_schemes, range_org_kinds,');
  L.push('  path_weight, is_symmetric, is_structural, excluded_from_path_intermediates)');
  L.push('VALUES');
  const arr = (v: string[]): string =>
    v.length ? `ARRAY[${v.map((x) => `'${x}'`).join(',')}]::text[]` : 'NULL';
  const rows = predicateNames.map((n) => {
    const p = onto.predicates[n]!;
    const inv = onto.predicates[p.inverse];
    // Inverses are not themselves declared predicates, so derive a readable
    // label from the name rather than reusing the forward one.
    const invLabel = inv ? inv.label : p.inverse.replace(/_/g, ' ');
    const dom = [...new Set(p.domain.map(baseType))];
    const rng = [...new Set(p.range.map(baseType))];
    const schemes = p.range
      .filter((r) => baseType(r) === 'concept')
      .map(subType)
      .filter(Boolean) as string[];
    const orgKinds = p.range
      .filter((r) => baseType(r) === 'organization')
      .map(subType)
      .filter(Boolean) as string[];
    return `  ('${n}', ${q(p.label)}, '${p.inverse}', ${q(invLabel)}, '${p.storage}', ${arr(dom)}, ${arr(rng)}, ${arr(schemes)}, ${arr(orgKinds)}, ${p.path_weight ?? 'NULL'}, ${Boolean(p.symmetric)}, ${Boolean(p.structural)}, ${Boolean(p.excluded_from_path_intermediates)})`;
  });
  L.push(rows.join(',\n') + ';');
  L.push('');

  L.push('-- Generic domain/range/subtype enforcement driven entirely by the table above.');
  L.push('CREATE OR REPLACE FUNCTION core.assert_edge_valid() RETURNS trigger AS $$');
  L.push('DECLARE m core.predicate_meta%ROWTYPE; obj_scheme text; obj_kind text;');
  L.push('BEGIN');
  L.push('  SELECT * INTO m FROM core.predicate_meta WHERE predicate = NEW.predicate;');
  L.push('  IF NOT FOUND THEN');
  L.push(`    RAISE EXCEPTION 'predicate % is not declared in ontology.yaml', NEW.predicate;`);
  L.push('  END IF;');
  L.push('');
  L.push("  IF m.storage <> TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME THEN");
  L.push(`    RAISE EXCEPTION 'predicate % is stored in %, not %.%',`);
  L.push('      NEW.predicate, m.storage, TG_TABLE_SCHEMA, TG_TABLE_NAME;');
  L.push('  END IF;');
  L.push('');
  L.push('  IF NOT (NEW.subject_type = ANY (m.domain_types)) THEN');
  L.push(`    RAISE EXCEPTION 'ontology violation: % subject must be one of %, got %',`);
  L.push('      NEW.predicate, m.domain_types, NEW.subject_type;');
  L.push('  END IF;');
  L.push('  IF NOT (NEW.object_type = ANY (m.range_types)) THEN');
  L.push(`    RAISE EXCEPTION 'ontology violation: % object must be one of %, got %',`);
  L.push('      NEW.predicate, m.range_types, NEW.object_type;');
  L.push('  END IF;');
  L.push('');
  L.push("  IF m.range_concept_schemes IS NOT NULL AND NEW.object_type = 'concept' THEN");
  L.push('    SELECT scheme INTO obj_scheme FROM core.concept WHERE id = NEW.object_id;');
  L.push('    IF obj_scheme IS NULL OR NOT (obj_scheme = ANY (m.range_concept_schemes)) THEN');
  L.push(`      RAISE EXCEPTION 'ontology violation: % requires a concept in scheme %, got %',`);
  L.push("        NEW.predicate, m.range_concept_schemes, coalesce(obj_scheme, '<missing>');");
  L.push('    END IF;');
  L.push('  END IF;');
  L.push('');
  L.push("  IF m.range_org_kinds IS NOT NULL AND NEW.object_type = 'organization' THEN");
  L.push('    SELECT kind INTO obj_kind FROM core.organization WHERE id = NEW.object_id;');
  L.push('    IF obj_kind IS NULL OR NOT (obj_kind = ANY (m.range_org_kinds)) THEN');
  L.push(
    `      RAISE EXCEPTION 'ontology violation: % requires an organization of kind %, got %',`,
  );
  L.push("        NEW.predicate, m.range_org_kinds, coalesce(obj_kind, '<missing>');");
  L.push('    END IF;');
  L.push('  END IF;');
  L.push('');
  L.push('  RETURN NEW;');
  L.push('END;');
  L.push('$$ LANGUAGE plpgsql;');
  L.push('');

  for (const t of ['core.edge', 'core.edge_derived']) {
    const trig = t.replace('.', '_');
    L.push(`DROP TRIGGER IF EXISTS ${trig}_assert_valid ON ${t};`);
    L.push(`CREATE TRIGGER ${trig}_assert_valid BEFORE INSERT OR UPDATE ON ${t}`);
    L.push('  FOR EACH ROW EXECUTE FUNCTION core.assert_edge_valid();', '');
  }
  return L.join('\n');
}

// -------------------------------------------------------------------- Markdown
function emitDocs(): string {
  const L: string[] = [];
  L.push('# Ontology reference');
  L.push('');
  L.push('<!-- GENERATED BY `pnpm codegen` FROM ontology/ontology.yaml — DO NOT EDIT. -->');
  L.push('');
  L.push('For the reasoning behind these choices — why Person is an entity and Actor is a role,');
  L.push(
    'why availability is not an edge, what we deliberately did not model — see [ontology.md](ontology.md).',
  );
  L.push('');
  L.push(
    `Ontology version ${onto.version}. ${predicateNames.length} predicates, ${entityNames.filter((n) => onto.entity_types[n]!.graph_node).length} graph node types.`,
  );
  L.push('');
  L.push('## Entity types');
  L.push('');
  L.push('| Type | Table | Graph node | Public page | Subtypes |');
  L.push('|---|---|---|---|---|');
  for (const n of entityNames) {
    const e = onto.entity_types[n]!;
    const sub = e.subtypes ? e.subtypes.values.join(', ') : '—';
    L.push(
      `| \`${n}\` | \`${e.table}\` | ${e.graph_node ? 'yes' : 'no'} | ${e.public_page ? 'yes' : 'no'} | ${sub} |`,
    );
  }
  L.push('');
  L.push('## Concept schemes');
  L.push('');
  L.push('| Scheme | Curated | Source | Hierarchical |');
  L.push('|---|---|---|---|');
  for (const [n, s] of Object.entries(onto.concept_schemes)) {
    L.push(
      `| \`${n}\` | ${s.curated ? 'yes' : 'no'} | \`${s.source}\` | ${s.hierarchical ? 'yes' : 'no'} |`,
    );
  }
  L.push('');
  L.push('## Predicates');
  L.push('');
  L.push('Path weight: lower is more meaningful in an explanation path.');
  L.push('');
  L.push('| Predicate | Domain | Range | Inverse | Storage | Weight | Provenance |');
  L.push('|---|---|---|---|---|---|---|');
  for (const n of predicateNames) {
    const p = onto.predicates[n]!;
    const w = p.structural ? '—' : String(p.path_weight);
    L.push(
      `| \`${n}\` | ${p.domain.map((d) => `\`${d}\``).join(', ')} | ${p.range.map((r) => `\`${r}\``).join(', ')} | \`${p.inverse}\` | \`${p.storage}\` | ${w} | ${p.provenance.join(', ')} |`,
    );
  }
  L.push('');
  L.push('## Narration templates');
  L.push('');
  L.push('Path explanations are composed from these. No model is involved.');
  L.push('');
  for (const n of predicateNames) {
    L.push(`- \`${n}\` — ${onto.predicates[n]!.narration}`);
  }
  return L.join('\n');
}

validate();
console.log('ontology: valid');
write('src/lib/ontology/generated.ts', emitTypes());
write('drizzle/generated/ontology.sql', emitSql());
write('docs/ontology-reference.md', emitDocs());
console.log('codegen: done');
